#!/bin/sh
#ghci -ignore-dot-ghci -ghci-script /usr/local/share/edprelude/.ghci -i/usr/local/share/edprelude -XDeriveGeneric -XDeriveAnyClass -XNoImplicitPrelude -interactive-print=print "$@"
ghci -i/usr/local/share/edprelude -XNoImplicitPrelude "$@"
